sudo: required
services:
  - docker
language: groovy
before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker run -d -p 27017:27017 mongo:latest
script:
  - "./gradlew assemble"
  - docker build -t sdkman/sdkman-announce:1.0.0-SNAPSHOT .
  - docker run -d -p 8080:8080 --net=host sdkman/sdkman-announce:1.0.0-SNAPSHOT
  - "./gradlew check"
after_success:
  - docker push sdkman/sdkman-announce:1.0.0-SNAPSHOT
cache:
  directories:
  - "$HOME/.gradle"
env:
  global:
