sudo: required
services:
  - docker
language: groovy
before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker run -d -p 27017:27017 mongo:latest
script:
  - docker build -t sdkman/vendor-announce:2.0.2 .
  - docker run -d -p 9001:9001 --net=host sdkman/vendor-announce:2.0.2
  - "./gradlew check"
after_success:
  - docker push sdkman/vendor-announce:2.0.2
cache:
  directories:
  - "$HOME/.gradle"
env:
  global:
  - secure: WP+O/b8GCp2vxCyawYBdRAZWGKWB/fFttk1QhPzHtqm3Cyfdkj+CCXqP+4S+zvpKXn9VFtz4ouSh0A3LiwmjIfLI3b2egZyH9anfgAv7CERNCJvMdrlo+ajvhrmMS2Bk23KgI0RrXTvYpGPdYkuXTlze6tuZE9fSA/1N862KkTLErByaP27IY8Dw7XDWwGLDTtbK8xEPl54ovjsXz1BQg/DHSaheInZcUdYUu3BqSDtFKYnJhMt2leuouvMmMQDQYjqV3Ts4fnwc3Gz7M4Erit5NyfJ+FT1xwMcMw9xLrskoO6S8lu6ld3x7ED/6uldXS70y7nyp0o5hJDjLGgJOKhZBZ8+QKV/N6EMYFO1AQ8yfLJXfK3ZHE7aIECOHwIGRfWzDdIJJ4rvxvYlvSIziReuUDDQbeGdpGsXCB2mu+Z7MjunYjUlxN+DXhH+mGdFa2GiUhGdVYmWLkgsqIdA75M3sxYj9jP5pLoTXMfLhbf/ox/OUfJxya0KVFj8siFFshQPJ0rybd/o9soSX+Z0qhGwLIrHh0tyqYgaxlEoGLqFAFqcaDO/2QisYu4TIXaRrN/jjoHXluwR1Y+okADNycnzTKPJXop66XYxbhYaUW01wR6eiNHM9mAB3Y5FGFzYV0l4FQ+7yYmJBN/6SfNpYWjJVgkGuxMe+w8AhEWIxXrw=
  - secure: CiqFmXFubUv3S1V9ziyrezJpu0+YhLV9C7W13Nb86Ti77yTHRlvtnEOatgGQc5znyCSmsig6SsFTC7neeYL9vN/YnwcUxjAObJTFxZ70LDKnkf2DTgqmGR0gebJrgeN5S/oLglQuHeym1jo/9DxeVFKfHnaXzneUHIc9+FuawPIbaQz1PnRNjXo9/6LfhCUskpsAbyS26ZqTseZrn4eci9D/SY4HCn5Mw9ax45A/SsiRNfe6fVOQaAeU/LiZt9QLdk0sYd+B9SKZmJ9+Q0UogNE3mkp3z3UB9rVXrFNz4mP06IzGYq0EZSzmh6FP3UZQwgxoVRY62/3uOtb1fVcGwcgx7QregH6sxQ33zi/CQnpLxP7AE/dkAuQpUHbCngg8oVn8VP23k7wuJ+LsGa0YTfYMf284oXbPb7Mx/CLeYn6aJDEIlt3Ar3LFAMGukfZoQsHjnqpGKIsHPGdPRfvrt4LlezA+xcCIOHt/GceKav9Tkk5IbA60e3pzFdO2Wg9YBY95gEA7Tg7pd2+jQvYI3285IOv/BlKEIN3SJAGwvgyEit53Yl9Etcf/K/x4rp3lKcBba4dHaMRHR5GHpRKg1zifcJlQR1b/Nf8UFQhz0atHtuT55lKOEYA1l8pU78/UOqMGlglTQMUw2jY0//e3UkqOvTd58njJJXvKiVse0io=
  - secure: bFSzRLGkSCGJv/6WG3ZL14NkWQau2wToEqSCZSBGP4MqXByuarj+yR/eoJZuv1Yv7T0X32WlN0DIPqkS1P2KRLuL8lrIqXsnQDqL9JJKqnmsyv9gOK9CauTwjq4XKpZHrpqza2V4yABgmQWqfa/foz5twnRezw/Jpuc6U/GTQwyCgaCN1A9yi++lx9yVmYzUR7X97TBvviNa+MLY4VPxNp+Om8LOSrizSZQ/tKKOUf1Q1tHvJJo0EXA/iwTE6qllRABu44ULRTCzLASD3+02p7KXMgm0W+eQvIhGkNHLNyCByMHEcI7GPaVW04cW3InTnaqycrMlTP1WDE2X5o7cfE2iqxEgITMdHXJyXkBrFNE/y09Y14OIBrJl+X43kVjPPUB2WVUdySHGlka92FqIb0y6LcgLGbIs+e1YcuO3jgzW8ja0ndvQxd0G61xOeRckkVYh/EpzHZsUvSLY+7ikkGkOjsh2Rd3NdKwS3UfGuXhM/Rl+P8ARI2x0KFyO7g3RZ/o1+jci3MPRhAIcl2oC7nlskIHub8D8NLllJLmJ7fNZRNCPDe3Rg7vYr5tcYQKYYyvngIC9qlxhveeeBcWEAW1dNAqpzmQoEUXVESbD96ecFsIuYTb4aKWYI4j/MdL3L1CQTRiwDMzhlgvz8rVDDVUZ4+kRTjgAIMIJ5zscIhg=

# blacklist
branches:
  except:
  - RELEASE
#
