sudo: required
services:
  - docker
language: groovy
before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker run -d -p 27017:27017 mongo:latest
script:
  - docker build -t sdkman/vendor-announce:2.0.0-SNAPSHOT .
  - docker run -d --net=host sdkman/vendor-announce:2.0.0-SNAPSHOT
  - "./gradlew check"
after_success:
  - docker push sdkman/vendor-announce:2.0.0-SNAPSHOT
cache:
  directories:
  - "$HOME/.gradle"
# blacklist
branches:
  except:
  - RELEASE
