sudo: required
services:
  - docker
language: groovy
before_install:
  - docker run -d -p 27017:27017 mongo:latest
script:
  - docker build -t sdkman/sdkman-announce:2.0.0-SNAPSHOT .
  - docker run -d -p 9001:9001 --net=host sdkman/sdkman-announce:2.0.0-SNAPSHOT
  - "./gradlew check"
after_success:
  - docker push sdkman/sdkman-announce:2.0.0-SNAPSHOT
cache:
  directories:
  - "$HOME/.gradle"
